import sanitize, { htmlToModerationText } from "@/utils/sanitize";

type BadWordsResult =
  | { success: false; message: string }
  | { success: true; message: string };

type ModeratedUserText =
  | { success: false; message: string }
  | { success: true; message: string; sanitized: string };

/**
 * Block player-authored text that matches the offensive-word list.
 * HTML is reduced to visible text first so markup and entities cannot hide a match.
 */
export const checkForBadWords = async (content: string): Promise<BadWordsResult> => {
  const visibleText = htmlToModerationText(content);
  // Only horizontal whitespace and hyphens may connect phrase tokens. Sentence,
  // clause, and line boundaries start a new run so phrases cannot match across them.
  const tokenRuns =
    visibleText
      .toLowerCase()
      .match(/\w+(?:(?:[ \t]+|-+)\w+)*/g)
      ?.map((run) => run.match(/\w+/g) ?? []) ?? [];
  const words = tokenRuns.flat();
  const foundWord = words.find((word) => OFFENSIVE_SINGLE_WORDS.has(word));
  if (foundWord) {
    return {
      success: false,
      message: `Your text was flagged for inappropriate language and will not be shown to others. Details: ${foundWord}`,
    };
  }
  for (const run of tokenRuns) {
    for (const phrase of OFFENSIVE_PHRASES) {
      for (let i = 0; i <= run.length - phrase.length; i++) {
        if (phrase.every((token, j) => run[i + j] === token)) {
          return {
            success: false,
            message: `Your text was flagged for inappropriate language and will not be shown to others. Details: ${phrase.join(" ")}`,
          };
        }
      }
    }
  }
  return { success: true, message: "Text passed moderation" };
};

/**
 * Block offensive language, then HTML-sanitize. Use on player-authored
 * bodies that are stored as HTML. Names and titles should call
 * checkForBadWords only.
 */
export const moderateUserText = async (content: string): Promise<ModeratedUserText> => {
  const moderationResult = await checkForBadWords(content);
  if (!moderationResult.success) return moderationResult;
  return {
    success: true,
    message: moderationResult.message,
    sanitized: sanitize(content),
  };
};

/**
 * List of potentially offensive words
 * Taken from: https://potentiallyoffensive.com/
 */
export const OFFENSIVE_WORDS = new Set([
  "assfuck",
  "a-rab",
  "abeed",
  "abo",
  "africoon",
  "africoon-americoon",
  "africoonia",
  "afro engineering",
  "ah chah",
  "alligator bait",
  "alligatorbait",
  "americoon",
  "americunt",
  "amerikkkunt",
  "anal",
  "analannie",
  "analsex",
  "anchor-baby",
  "antifaggot",
  "antinigger",
  "aperest",
  "apesault",
  "arabush",
  "aravush",
  "areola",
  "armo",
  "arse",
  "arsehole",
  "aseng",
  "ashke-nazi",
  "ass",
  "assbagger",
  "assblaster",
  "assburgers",
  "assclown",
  "asscowboy",
  "asses",
  "assfucker",
  "asshole",
  "assholes",
  "asshore",
  "assjockey",
  "asskisser",
  "assklown",
  "asslick",
  "asslicker",
  "asslover",
  "assman",
  "assmonkey",
  "assmunch",
  "assmuncher",
  "asspacker",
  "asspirate",
  "asspuppies",
  "assranger",
  "asswhore",
  "asswipe",
  "aunt-jemima",
  "ayrab",
  "backdoorman",
  "badfuck",
  "bakra",
  "balija",
  "ballgag",
  "balllicker",
  "ballsack",
  "barelylegal",
  "bastard",
  "bazongas",
  "bazooms",
  "beaner",
  "beaney",
  "beatoff",
  "beatyourmeat",
  "beef curtains",
  "bellend",
  "bestial",
  "bigass",
  "bigbastard",
  "bigbutt",
  "b1tch",
  "b1tches",
  "b1tchez",
  "bitch",
  "bitches",
  "bitchez",
  "bitchslap",
  "blackman",
  "blacks",
  "bluegum",
  "blumpkin",
  "boche",
  "bog-irish",
  "bogan",
  "bogtrotter",
  "bohunk",
  "bollock",
  "bombing",
  "bondage",
  "boong",
  "boonga",
  "bootlip",
  "bootycall",
  "bougnoule",
  "bountybar",
  "bozgor",
  "brea5t",
  "breastman",
  "buckra",
  "buddhahead",
  "buggery",
  "bule",
  "bullcrap",
  "bulldike",
  "bulldyke",
  "bullshit",
  "bumblefuck",
  "bumfuck",
  "bung",
  "bunghole",
  "burr-head",
  "burrhead",
  "butchbabes",
  "butchdike",
  "butchdyke",
  "butt-bang",
  "butt-fuck",
  "butt-fucker",
  "butt-fuckers",
  "buttbang",
  "buttface",
  "buttfuck",
  "buttfucker",
  "buttfuckers",
  "buttman",
  "buttmunch",
  "buttpirate",
  "cabbage-eater",
  "camel-jockey",
  "cameljockey",
  "carcamano",
  "carpet-muncher",
  "carpetmuncher",
  "carruth",
  "catfucker",
  "cawk",
  "chankoro",
  "chav",
  "cheesedick",
  "chernozhopy",
  "chinaman",
  "chinamen",
  "chink",
  "choad",
  "chode",
  "chug",
  "ciapaty-or-ciapak",
  "cina",
  "clamdigger",
  "clamdiver",
  "clit",
  "clunge",
  "cock",
  "cockcowboy",
  "cockknob",
  "cocklover",
  "cockrider",
  "cocksmith",
  "cocksmoker",
  "cocksucer",
  "cocksucker",
  "cocksucking",
  "cocktease",
  "cokin",
  "coloured",
  "cooly",
  "coon",
  "coon-ass",
  "cooter",
  "cornhole",
  "crackwhore",
  "crotchmonkey",
  "crotchrot",
  "cum",
  "cumbubble",
  "cumfest",
  "cummer",
  "cumming",
  "cumquat",
  "cumqueen",
  "cumshot",
  "cumskin",
  "cumsock",
  "cunilingus",
  "cunnilingus",
  "cunt",
  "cunteyed",
  "cuntfucker",
  "cuntlicker",
  "datnigga",
  "deepthroat",
  "defecate",
  "dego",
  "deth",
  "dhoti",
  "dick",
  "dickbrain",
  "dickforbrains",
  "dickless",
  "dicklick",
  "dicklicker",
  "diddle",
  "dike",
  "dixiedyke",
  "doggiestyle",
  "doggystyle",
  "dong",
  "dothead",
  "douche",
  "douchebag",
  "dripdick",
  "dullard",
  "ejaculation",
  "erection",
  "faeces",
  "fag",
  "faggot",
  "faggotry",
  "faggots",
  "faggoty",
  "fagot",
  "fannyfucker",
  "fastfuck",
  "fatass",
  "fatfuck",
  "fatfucker",
  "fatso",
  "fckcum",
  "feces",
  "felatio",
  "femsplaining",
  "fritzie",
  "frogess",
  "fuck",
  "fucked",
  "fucker",
  "fuckers",
  "fucking",
  "fucks",
  "fuc",
  "fucc",
  "fuk",
  "fukk",
  "fuck-you",
  "fuckity-bye",
  "fucktardedly",
  "fucktardedness",
  "fuuck",
  "fux",
  "goldenshower",
  "golliwog",
  "gonzagas",
  "goyim",
  "greaseball",
  "greaser",
  "gringo",
  "groe",
  "gyopo",
  "gypsy",
  "half-breed",
  "handjob",
  "hobo",
  "hoes",
  "homobangers",
  "homosexual",
  "hooters",
  "hore",
  "horney",
  "hunky",
  "hussy",
  "hymie",
  "iceberg fuckers",
  "incest",
  "indognesial",
  "indonesial",
  "jackoff",
  "jew",
  "jigaboo",
  "jigg",
  "jigga",
  "jiggabo",
  "jigger",
  "jiggy",
  "jihad",
  "jijjiboo",
  "jism",
  "jiz",
  "jizjuice",
  "jizm",
  "jizzim",
  "jizzum",
  "knockers",
  "kummer",
  "kumming",
  "kumquat",
  "kunilingus",
  "kunt",
  "ky",
  "kyke",
  "laid",
  "laowai",
  "latinx",
  "leb",
  "lebo",
  "looney",
  "mangal",
  "minge",
  "minger",
  "molester",
  "molestor",
  "moneyshot",
  "moolinyan",
  "moon-cricket",
  "mooncricket",
  "moskal",
  "mothafucka",
  "motherfucker",
  "motherfucking",
  "motherfuckings",
  "mountain-turk",
  "muff",
  "muffdive",
  "munt",
  "munter",
  "mzungu",
  "n1gga",
  "n1gga$",
  "n1ggas",
  "n1ggaz",
  "nigga",
  "nigga$",
  "niggas",
  "niggaz",
  "nigger",
  "niggerhole",
  "niggers",
  "niggles",
  "niggling",
  "nigglings",
  "nizzle",
  "nlgger",
  "nlggor",
  "nofuckingway",
  "nookey",
  "nookie",
  "nooner",
  "norte",
  "orgasim",
  "orgasm",
  "orgies",
  "orgy",
  "oriental",
  "osama",
  "oven-dodger",
  "paleface",
  "pansy",
  "pecker",
  "peckerwood",
  "peehole",
  "peepshow",
  "penis",
  "perv",
  "petrol-sniffer",
  "phonesex",
  "phuk",
  "phuked",
  "phuking",
  "phukking",
  "phungky",
  "phuq",
  "pi55",
  "picaninny",
  "piccaninny",
  "piefke",
  "polentone",
  "polock",
  "poon",
  "poontang",
  "poorwhitetrash",
  "porch-monkey",
  "porchmonkey",
  "porn",
  "pornflick",
  "pornking",
  "porno",
  "prickhead",
  "prostitute",
  "pshek",
  "pu55i",
  "pu55y",
  "pubiclice",
  "pud",
  "punani",
  "queer",
  "redskin",
  "retard",
  "retarded",
  "sexslave",
  "sextogo",
  "sexwhore",
  "shag",
  "sheboon",
  "sheepfucker",
  "shinola",
  "shit",
  "shit for brains",
  "shitcan",
  "shitdick",
  "shiteater",
  "shitface",
  "shitfit",
  "shitforbrains",
  "shitfuck",
  "shitfull",
  "shithapens",
  "shithappens",
  "shithead",
  "shitnigger",
  "shits",
  "slanteye",
  "slav",
  "slavedriver",
  "sleezeball",
  "slimeball",
  "slut",
  "sluts",
  "slutt",
  "sniggers",
  "snowback",
  "snownigger",
  "spaghettinigger",
  "spankthemonkey",
  "spearchucker",
  "spermbag",
  "spermhearder",
  "spermherder",
  "spic",
  "spick",
  "spitter",
  "stiffy",
  "strapon",
  "stupidfuck",
  "stupidfucker",
  "suckdick",
  "suckme",
  "suckmyass",
  "suckmydick",
  "suckmytit",
  "suckoff",
  "swamp-guinea",
  "swastika",
  "tacohead",
  "tatas",
  "timber-nigger",
  "titbitnipply",
  "titfuck",
  "titfucker",
  "towel-head",
  "trannie",
  "tranny",
  "trans-testicle",
  "transgendered",
  "trisexual",
  "troid",
  "trots",
  "turco-albanian",
  "twat",
  "twink",
  "twinkie",
  "twobitwhore",
  "uncle-tom",
  "unfuckable",
  "vatnik",
  "welfare queen",
  "wetback",
  "whiskeydick",
  "white-trash",
  "whitetrash",
  "whitewashing",
  "whop",
  "wigger",
  "wuhan-virus",
  "yambag",
  "yuon",
  "zhid",
  "zhidovka",
  "zhyd",
  "zhydovka",
  "zigabo",
]);

/**
 * Split every list entry on non-word characters. Single-token results
 * (e.g. "nigga$") join the word set; multi-token runs (e.g. "towel-head")
 * become consecutive-phrase matches. No entry can fall through.
 */
const normalized = [...OFFENSIVE_WORDS].map((w) => w.split(/\W+/).filter(Boolean));
const OFFENSIVE_SINGLE_WORDS = new Set(
  normalized.flatMap((phrase) => (phrase.length === 1 ? phrase : [])),
);
const OFFENSIVE_PHRASES = normalized.filter((p) => p.length > 1);
